spring:
  thymeleaf:
    cache: false

zookeeper:
  zookeeperHosts: 10.0.0.215:2181,10.0.0.215:2182,10.0.0.215:2183
  sessionTimeoutMs: 10000
  connectionTimeoutMs: 10000

kafka:
  host: 10.0.0.215
  port: 9092
  soTimeout: 100000
  bufferSize: 65536
  clientId: producer
  serializerClass: kafka.serializer.StringEncoder
  partitionerClass: com.javabilities.producer.service.SimplePartitioner
  requestRequiredAcks: 1
  numPartitions: 1
  replicationFactor: 1

consumer:
  topic: topic-01
  messageKey: key-01
