spring:
  thymeleaf:
    cache: false

zookeeper:
  zookeeperHosts: 127.0.0.1:2181
  sessionTimeoutMs: 10000
  connectionTimeoutMs: 10000

kafka:
  host: 127.0.0.1
  port: 9092
  soTimeout: 100000
  bufferSize: 65536
  clientId: producer
  serializerClass: kafka.serializer.StringEncoder
  partitionerClass: com.javabilities.producer.service.SimplePartitioner
  requestRequiredAcks: 1
  numPartitions: 1
  replicationFactor: 1
